name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOC_USER }}
          password: ${{ secrets.DOC_PASS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOC_USER }}/my_app:${{ github.sha }} .
          docker tag ${{ secrets.DOC_USER }}/my_app:${{ github.sha }} ${{ secrets.DOC_USER }}/my_app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOC_USER }}/my_app:${{ github.sha }}
          docker push ${{ secrets.DOC_USER }}/my_app:latest
